plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Env: dev
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: ""
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address


